-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 22:43:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Renta_Car
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Renta_Car
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Renta_Car` DEFAULT CHARACTER SET utf8 ;
USE `Renta_Car` ;

-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_cliente` (
  `ID_cliente` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATE NULL,
  `numero_licencia` DATE NULL,
  `num_identificacion` DATETIME NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `direccion` VARCHAR(400) NULL,
  `numero_telefonico` VARCHAR(25) NULL,
  `correo_electronico` VARCHAR(150) NULL,
  `edad` DATE NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_ofina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_ofina` (
  `ID_Oficina` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `telefono` VARCHAR(25) NULL,
  `direccion` VARCHAR(200) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Oficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_Vehiculo` (
  `ID_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `num_puertas` VARCHAR(45) NULL,
  `kilometraje` VARCHAR(45) NULL,
  `num_asientos` VARCHAR(45) NULL,
  `año` INT NULL,
  `numero_VIN` VARCHAR(45) NULL,
  `tipo_transmision` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_Tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_Tarifa` (
  `ID_tarifas` INT NOT NULL AUTO_INCREMENT,
  `precio_servicio` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `TBL_ID_vehiculo` INT NOT NULL,
  PRIMARY KEY (`ID_tarifas`),
  INDEX `fk_TBL_Tarifa_TBL_Vehiculo1_idx` (`TBL_ID_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_Tarifa_TBL_Vehiculo1`
    FOREIGN KEY (`TBL_ID_vehiculo`)
    REFERENCES `Renta_Car`.`TBL_Vehiculo` (`ID_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_solicitud` (
  `ID_solicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATETIME NULL,
  `fecha_hora_devolucion` DATETIME NULL,
  `oficina_devolucion` VARCHAR(45) NULL,
  `oficina_retiro` VARCHAR(45) NULL,
  `fecha_hora_retiro` DATETIME NULL,
  `TBL_ID_cliente` INT NOT NULL,
  `TBL_ID_Oficina` INT NOT NULL,
  `TBL_ID_tarifas` INT NOT NULL,
  PRIMARY KEY (`ID_solicitud`),
  INDEX `fk_TBL_solicitud_TBL_cliente_idx` (`TBL_ID_cliente` ASC) VISIBLE,
  INDEX `fk_TBL_solicitud_TBL_ofina1_idx` (`TBL_ID_Oficina` ASC) VISIBLE,
  INDEX `fk_TBL_solicitud_TBL_Tarifa1_idx` (`TBL_ID_tarifas` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_solicitud_TBL_cliente`
    FOREIGN KEY (`TBL_ID_cliente`)
    REFERENCES `Renta_Car`.`TBL_cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_solicitud_TBL_ofina1`
    FOREIGN KEY (`TBL_ID_Oficina`)
    REFERENCES `Renta_Car`.`TBL_ofina` (`ID_Oficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_solicitud_TBL_Tarifa1`
    FOREIGN KEY (`TBL_ID_tarifas`)
    REFERENCES `Renta_Car`.`TBL_Tarifa` (`ID_tarifas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_referencia` (
  `ID_persona_contacto` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATETIME NULL,
  `num_identificacion` DATETIME NULL,
  `nombre_completo` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `num_telefono` VARCHAR(25) NULL,
  `correo_electronico` VARCHAR(150) NULL,
  `parentesco` VARCHAR(45) NULL,
  `TBL_ID_cliente` INT NOT NULL,
  PRIMARY KEY (`ID_persona_contacto`),
  INDEX `fk_TBL_referencia_TBL_cliente1_idx` (`TBL_ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_referencia_TBL_cliente1`
    FOREIGN KEY (`TBL_ID_cliente`)
    REFERENCES `Renta_Car`.`TBL_cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_trabajo` (
  `ID_trabajo` INT NOT NULL,
  `TBL_cliente_ID_cliente` INT NOT NULL,
  `Nombre_trabajo` VARCHAR(45) NULL,
  `Lugar_trabajo` VARCHAR(45) NULL,
  `Ocupacion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_trabajo`),
  INDEX `fk_TBL_trabajo_TBL_cliente1_idx` (`TBL_cliente_ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_trabajo_TBL_cliente1`
    FOREIGN KEY (`TBL_cliente_ID_cliente`)
    REFERENCES `Renta_Car`.`TBL_cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_Licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_Licencia` (
  `ID_Licencia` INT NOT NULL,
  `Tipo_Licencia` VARCHAR(45) NULL,
  `Fecha_Vencimiento` VARCHAR(45) NULL,
  `TBL_cliente_ID_cliente` INT NOT NULL,
  PRIMARY KEY (`ID_Licencia`),
  INDEX `fk_TBL_Licencia_TBL_cliente1_idx` (`TBL_cliente_ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_Licencia_TBL_cliente1`
    FOREIGN KEY (`TBL_cliente_ID_cliente`)
    REFERENCES `Renta_Car`.`TBL_cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`Marca` (
  `ID_marca` INT NOT NULL,
  `Nombre_marca` VARCHAR(45) NULL,
  `País_origen` VARCHAR(45) NULL,
  `TBL_Vehiculo_ID_vehiculo` INT NOT NULL,
  PRIMARY KEY (`ID_marca`),
  INDEX `fk_Marca_TBL_Vehiculo1_idx` (`TBL_Vehiculo_ID_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_TBL_Vehiculo1`
    FOREIGN KEY (`TBL_Vehiculo_ID_vehiculo`)
    REFERENCES `Renta_Car`.`TBL_Vehiculo` (`ID_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_modelo` (
  `ID_modelo` INT NOT NULL,
  `Nombre_modelo` VARCHAR(45) NULL,
  `Tipo_motor` VARCHAR(45) NULL,
  `Marca_ID_marca` INT NOT NULL,
  PRIMARY KEY (`ID_modelo`),
  INDEX `fk_TBL_modelo_Marca1_idx` (`Marca_ID_marca` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_modelo_Marca1`
    FOREIGN KEY (`Marca_ID_marca`)
    REFERENCES `Renta_Car`.`Marca` (`ID_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_matricula` (
  `ID_matricula` INT NOT NULL,
  `Fecha_matricula` VARCHAR(45) NULL,
  `Fecha_vencimiento` VARCHAR(45) NULL,
  `Lugar_registro` VARCHAR(45) NULL,
  `TBL_Vehiculo_ID_vehiculo` INT NOT NULL,
  PRIMARY KEY (`ID_matricula`),
  INDEX `fk_TBL_matricula_TBL_Vehiculo1_idx` (`TBL_Vehiculo_ID_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_matricula_TBL_Vehiculo1`
    FOREIGN KEY (`TBL_Vehiculo_ID_vehiculo`)
    REFERENCES `Renta_Car`.`TBL_Vehiculo` (`ID_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_Nacionalidad_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_Nacionalidad_Cliente` (
  `ID_Nacionalidad` INT NOT NULL,
  `Pais_origen` VARCHAR(45) NULL,
  `Codigo_Postal` VARCHAR(45) NULL,
  `TBL_cliente_ID_cliente` INT NOT NULL,
  PRIMARY KEY (`ID_Nacionalidad`),
  INDEX `fk_TBL_Nacionalidad_Cliente_TBL_cliente1_idx` (`TBL_cliente_ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_Nacionalidad_Cliente_TBL_cliente1`
    FOREIGN KEY (`TBL_cliente_ID_cliente`)
    REFERENCES `Renta_Car`.`TBL_cliente` (`ID_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TB_tardanza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TB_tardanza` (
  `Id_tardanza` INT NOT NULL,
  `TBL_Tarifa_ID_tarifas` INT NOT NULL,
  `Tarifa_tardanza` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_tardanza`),
  INDEX `fk_TB_tardanza_TBL_Tarifa1_idx` (`TBL_Tarifa_ID_tarifas` ASC) VISIBLE,
  CONSTRAINT `fk_TB_tardanza_TBL_Tarifa1`
    FOREIGN KEY (`TBL_Tarifa_ID_tarifas`)
    REFERENCES `Renta_Car`.`TBL_Tarifa` (`ID_tarifas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_Seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_Seguro` (
  `ID_seguro` INT NOT NULL,
  `Nombre_seguro` VARCHAR(45) NULL,
  `Tipo_seguro` VARCHAR(45) NULL,
  `TBL_Tarifa_ID_tarifas` INT NOT NULL,
  PRIMARY KEY (`ID_seguro`),
  INDEX `fk_TBL_Seguro_TBL_Tarifa1_idx` (`TBL_Tarifa_ID_tarifas` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_Seguro_TBL_Tarifa1`
    FOREIGN KEY (`TBL_Tarifa_ID_tarifas`)
    REFERENCES `Renta_Car`.`TBL_Tarifa` (`ID_tarifas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TLB_combustible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TLB_combustible` (
  `ID_combustible` INT NOT NULL,
  `Tipo_combustible` VARCHAR(45) NULL,
  `Nivel_octanaje` VARCHAR(45) NULL,
  `TBL_Vehiculo_ID_vehiculo` INT NOT NULL,
  PRIMARY KEY (`ID_combustible`),
  INDEX `fk_TLB_combustible_TBL_Vehiculo1_idx` (`TBL_Vehiculo_ID_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_TLB_combustible_TBL_Vehiculo1`
    FOREIGN KEY (`TBL_Vehiculo_ID_vehiculo`)
    REFERENCES `Renta_Car`.`TBL_Vehiculo` (`ID_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBLtipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBLtipo_vehiculo` (
  `ID_tipo_vehiculo` INT NOT NULL,
  `Nombre_tipo_vehiculo` VARCHAR(45) NULL,
  `TBL_modelo_ID_modelo` INT NOT NULL,
  PRIMARY KEY (`ID_tipo_vehiculo`),
  INDEX `fk_TBLtipo_vehiculo_TBL_modelo1_idx` (`TBL_modelo_ID_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_TBLtipo_vehiculo_TBL_modelo1`
    FOREIGN KEY (`TBL_modelo_ID_modelo`)
    REFERENCES `Renta_Car`.`TBL_modelo` (`ID_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Renta_Car`.`TBL_año`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Renta_Car`.`TBL_año` (
  `ID_año` INT NOT NULL,
  `Fabricacion` VARCHAR(45) NULL,
  `Lanzamiento` VARCHAR(45) NULL,
  `TBL_Vehiculo_ID_vehiculo` INT NOT NULL,
  PRIMARY KEY (`ID_año`),
  INDEX `fk_TBL_año_TBL_Vehiculo1_idx` (`TBL_Vehiculo_ID_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_año_TBL_Vehiculo1`
    FOREIGN KEY (`TBL_Vehiculo_ID_vehiculo`)
    REFERENCES `Renta_Car`.`TBL_Vehiculo` (`ID_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
